#pragma config(Sensor, S1,     SensorDireito,  sensorLightActive)
#pragma config(Sensor, S3,     SensorEsquerdo, sensorLightActive)
#pragma config(Motor,  motorA,          MotorDireito,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          MotorEsquerdo, tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//Definicao da velocidade base e do threshold do reflexo da luz quando o sensor estiver vendo a cor branca
#define VelocidadeBase 20
#define ReflexoLuz 47

task main(){

	while(true){

		//Se ambos os sensores estiverem vendo a cor preta, isos quer dizer que o robo pode seguir em linha reta
		if(SensorValue[S1] < ReflexoLuz && SensorValue[S3] < ReflexoLuz){
			motor[motorA] = VelocidadeBase;
			motor[motorB] = VelocidadeBase;
		}

		/*Se ambos os sensores estiverem vendo a cor branca, então o robo esta no meio de um cruzamento,
		portanto, deve seguir em linha reta*/
		else if(SensorValue[S1] >= ReflexoLuz && SensorValue[S3] >= ReflexoLuz){
			motor[motorA] = VelocidadeBase;
			motor[motorB] = VelocidadeBase;
		}

		//Caso contrario, o robo devera vazer uma curva
		else{

			//Se o sensor da direita estiver vendo a cor branca e o da esquerda a cor preta, então ele fazer curva a direita
			if(SensorValue[S1] >= ReflexoLuz){
				motor[motorA] = VelocidadeBase - 15;
				motor[motorB] = VelocidadeBase;
			}

			//Caso contrário, o robo deve fazer curva para a esquerda
			else{
				motor[motorA] = VelocidadeBase;
				motor[motorB] = VelocidadeBase - 15;
			}
		}
		wait10Msec(5);
	}
}
